image: yourlabs/python

py-qa:
  script: flake8 --show-source --max-complexity=8 --exclude migrations djcall --builtins=ModuleNotFoundError

py-test:
  script:
    - pip install -e .[django,example]
    - DEBUG=1 pytest -vv --strict -r fEsxXw

pypi:
  stage: deploy
  script: pypi-release
