image: yourlabs/python

py-qa:
  stage: test
  script: flake8 --show-source --max-complexity=8 --exclude migrations djcall --builtins=ModuleNotFoundError
  cache:
    paths: [.tox]

py-test:
  stage: test
  script: pip install . && py.test -vv --strict -r fEsxXw djcall

pypi:
  stage: deploy
  script: pypi-release
