image: yourlabs/python

py-qa:
  stage: test
  script: tox -e qa
  cache:
    paths: [.tox]

py-test:
  stage: test
  script: tox -e py36-dj21
  cache:
    paths: [.tox]

pypi:
  stage: deploy
  script: pypi-release
